import type { Metadata } from 'next';
import { Poppins, Inter, Dela_Gothic_One } from 'next/font/google';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import Navbar from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import Contact from '@/components/Contact/Contact';
import Head from 'next/head';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-poppins',
  display: 'swap',
});

const delta = Dela_Gothic_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-delta',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang='en'>
      <body className={GeistSans.className}>
        <Navbar />
        <div className='flex-col bg-scroll bg-auto bg-center'>
        </div>
        <Contact />
        <main className='flex min-h-screen flex-col bg-neutral'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
